global:
  qsname: quickstart-spinnaker
  owner: huynhz@amazon.com
  marketplace-ami: false
  reporting: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  spin-us-east-1:
    template_file: quickstart-spinnakercf.template
    parameter_input: quickstart-spinnakercf-us-east-1.json
    regions:
    - us-east-1
  spin-us-west-1:
    template_file: quickstart-spinnakercf.template
    parameter_input: quickstart-spinnakercf-us-west-1.json
    regions:
    - us-west-1
  spin-us-west-2:
    template_file: quickstart-spinnakercf.template
    parameter_input: quickstart-spinnakercf-us-west-2.json
    regions:
    - us-west-2
  spin-eu-west-1:
    template_file: quickstart-spinnakercf.template
    parameter_input: quickstart-spinnakercf-eu-west-1.json
    regions:
    - eu-west-1
